### ISSUE TITLE
Readme example

### ISSUE THREAD

**Issue by sethgrid** [polydawn/meep#3]
I'm having trouble following your README example. Can you give a more "real" example? Maybe how you would use it around json.Marshal? Or similar?

**Comment by warpfork** [comment]
Absolutely, never enough docs.  I drafted a bunch more.

There's now a pretty big example in the [readmore](https://github.com/polydawn/meep/blob/master/READMORE.md#a-bigger-example).  It's a little contrived, but I guess that's a given; hope it helps some.

**Comment by sethgrid** [comment]
that helps; thanks
